# Generated by Django 3.1.4 on 2021-01-05 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('main_phone_number', models.CharField(max_length=13)),
                ('office_phone_number', models.CharField(max_length=13)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('core', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('core', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('about', models.TextField()),
                ('picture', models.ImageField(upload_to='executives/images/%Y/')),
                ('active', models.BooleanField(verbose_name=True)),
                ('date_started', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('executive_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='pages.executiverole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-active', 'executive_role', 'date_created'),
            },
        ),
    ]
