# Generated by Django 3.1.4 on 2021-01-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executive',
            options={'ordering': ('-is_active', 'executive_role', 'date_created')},
        ),
        migrations.RenameField(
            model_name='executive',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='configuration',
            name='about',
            field=models.TextField(default='Hello this is the about section of the website'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executive',
            name='date_started',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='executive',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
