# Generated by Django 3.2.6 on 2021-08-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.URLField(blank=True),
        ),
    ]
