# Generated by Django 3.2.6 on 2021-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_event_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link_text',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
