# Generated by Django 3.1.4 on 2021-01-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='The venue', max_length=500),
            preserve_default=False,
        ),
    ]
