# Generated by Django 3.1.4 on 2021-01-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_book_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(1, 'Level 100'), (2, 'Level 200'), (3, 'Level 300'), (4, 'Level 400'), (5, 'Level 500'), (6, 'Level 600')])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='pages.programme')),
            ],
            options={
                'ordering': ('year', 'title'),
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='pages.course'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
