# Generated by Django 3.1.4 on 2021-01-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210119_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('course', 'title')},
        ),
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='pages.course'),
            preserve_default=False,
        ),
    ]
