# Generated by Django 3.1.4 on 2021-01-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
