# Generated by Django 3.1.4 on 2021-01-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210120_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
