# Generated by Django 3.1.4 on 2021-01-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
