# Generated by Django 3.1.4 on 2021-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210121_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='configuration',
            name='whatsapp_link',
            field=models.URLField(blank=True),
        ),
    ]
