# Generated by Django 3.1.4 on 2021-01-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210121_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
