# Generated by Django 3.1.4 on 2021-01-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_configuration_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiverole',
            name='duty',
            field=models.TextField(default='The president holds the core of the association he '),
            preserve_default=False,
        ),
    ]
