# Generated by Django 3.1.4 on 2021-02-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_madarasah_madarasahcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=13)),
                ('banner', models.ImageField(upload_to='business/banner/%Y/%m/')),
                ('slug', models.SlugField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=30)),
                ('slug', models.SlugField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(upload_to='products/%Y/%m/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.business')),
            ],
            options={
                'ordering': ('title', 'date'),
            },
        ),
    ]
