# Generated by Django 3.1.4 on 2021-02-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_business_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default="Sobolo is a fancy drink in ghana. I know you'll love it. Don't sweat"),
            preserve_default=False,
        ),
    ]
