# Generated by Django 3.1.4 on 2021-02-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='history',
            field=models.TextField(default='GMSA Ucc was founded on ..... and so on and so on'),
            preserve_default=False,
        ),
    ]
