# Generated by Django 3.1.4 on 2021-02-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('application_link', models.URLField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('date', 'title'),
            },
        ),
    ]
